DROP DATABASE IF EXISTS `twatBook_db`;

CREATE DATABASE `twatBook_db`;

USE DATABASE 'twatBook_db':

CREATE TABLE twatBook (
id INT AUTO_INCREMENT NOT NULL,
author VARCHAR(100) NOT NULL,
password VARCHAR(255) NOT NULL,
post VARCHAR(255) NOT NULL,
createdAt TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);